from .box_config import BOX_CONFIG
from .browserbase_config import BROWSERBASE_CONFIG
from .browserbase_filtered import BROWSERBASE_CONFIG_FILTERED
from .mongodb_config import MONGODB_CONFIG

CONFIGS = {
    "BROWSERBASE_CONFIG": BROWSERBASE_CONFIG,
    "BROWSERBASE_CONFIG_FILTERED": BROWSERBASE_CONFIG_FILTERED,
    "MONGODB_CONFIG": MONGODB_CONFIG,
    "BOX_CONFIG": BOX_CONFIG,
}

__all__ = ["BROWSERBASE_CONFIG", "BROWSERBASE_CONFIG_FILTERED", "MONGODB_CONFIG", "BOX_CONFIG", "CONFIGS"]
